//
// Created by Jan on 17.03.2017.
//

#ifndef GOLDENE_SIEBEN_CARD_VALUE_H
#define GOLDENE_SIEBEN_CARD_VALUE_H


enum CardValue {
    ASS, ZWEI, DREI, VIER, FUENF, SECHS, SIEBEN, BUBE, DAME, KOENIG
};


#endif //GOLDENE_SIEBEN_CARD_VALUE_H
